# Generated by Django 3.2.8 on 2021-10-29 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20211029_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choices',
            new_name='question',
        ),
    ]
